name: Polly Pipeline (Prod)

on:
    push:
        branches:
            - main

jobs: 
    run_polly:
        runs-on: ubuntu-latest
        env:
            S3_BUCKET: ${{ secrets.S3_BUCKET_PROD }}
            S3_PATH: ${{ secrets.S3_BUCKET_PROD_PATH }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up AWS CLI
              uses: aws-actions/configure-aws-credentials@v2
              with: 
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Convert txt to mp3 (prod)
              run: |
                  pip install boto3 --upgrade
                  python synthesize.py
                  aws s3 cp example.mp3 s3://$S3_BUCKET/$S3_PATH